### ISSUE TITLE
naked .il causes traceback

### ISSUE THREAD

**Issue by tallforasmurf** [wf49670/ppgen#88]
The following document causes a crash and traceback:

    .il
    .ca
    f673 <target id="Fig_673"><sc>Fig</sc>. 673.--Connections for two shunt wound dynamos to run in parallel. The positive lead of
    each machine is connected to the same bus bar. In starting, if but one machine is to be
    used, the dynamo is first brought up to speed and the voltage regulated by means of the
    rheostat R and the voltmeter V.
    .ca-

the traceback is:

    ppgen 3.52h
    creating UTF-8 text file
    Traceback (most recent call last):
      File "ppgen.py", line 9019, in <module>
        main()
      File "ppgen.py", line 9002, in main
        ppt.run()
      File "ppgen.py", line 5301, in run
        self.process()
      File "ppgen.py", line 5275, in process
        self.doDot()
      File "ppgen.py", line 1856, in doDot
            switch[0]()
      File "ppgen.py", line 4117, in doIllo
        self.crash_w_context("Malformed .il directive: {}".format(self.wb[self.cl]))
    TypeError: crash_w_context() missing 1 required positional argument: 'i'`

**Comment by wf49670** [comment]
On 8/20/2015 3:22 PM, Nat Picker wrote:
>
> The following document causes a crash and traceback:
>
> |.il .ca f673 <target id="Fig_673"><sc>Fig</sc>. 673.--Connections for 
> two shunt wound dynamos to run in parallel. The positive lead of each 
> machine is connected to the same bus bar. In starting, if but one 
> machine is to be used, the dynamo is first brought up to speed and the 
> voltage regulated by means of the rheostat R and the voltmeter V. .ca- |
>
> the traceback is:
>
> |ppgen 3.52h creating UTF-8 text file Traceback (most recent call 
> last): File "ppgen.py", line 9019, in <module> main() File "ppgen.py", 
> line 9002, in main ppt.run() File "ppgen.py", line 5301, in run 
> self.process() File "ppgen.py", line 5275, in process self.doDot() 
> File "ppgen.py", line 1856, in doDot switch[0]() File "ppgen.py", line 
> 4117, in doIllo self.crash_w_context("Malformed .il directive: 
> {}".format(self.wb[self.cl])) TypeError: crash_w_context() missing 1 
> required positional argument: 'i'` |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/wf49670/ppgen/issues/88>.
>
Thanks; I'll get that fixed.

**Comment by wf49670** [comment]
Fixed in current development release, 3.52j
